### Preprocessing

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn as sk

original_data_train = pd.read_csv(
    "adult.data",
    names=[
        "Age", "Workclass", "fnlwgt", "Education", "Education-Num", "Martial Status",
        "Occupation", "Relationship", "OrigEthn", "Sex", "Capital Gain", "Capital Loss",
        "Hours per week", "Country", "Target"],
    sep=r'\s*,\s*',
    engine='python',
    na_values="?")

original_data_test = pd.read_csv(
    "adult.test",
    names=[
        "Age", "Workclass", "fnlwgt", "Education", "Education-Num", "Martial Status",
        "Occupation", "Relationship", "OrigEthn", "Sex", "Capital Gain", "Capital Loss",
        "Hours per week", "Country", "Target"],
    sep=r'\s*,\s*',
    engine='python',
    na_values="?")


original_data = pd.concat([original_data_test,original_data_train])
original_data.reset_index(inplace = True, drop = True)

original_data.tail()



Age     Workclass    fnlwgt   Education  Education-Num  \
48838  27       Private  257302.0  Assoc-acdm           12.0   
48839  40       Private  154374.0     HS-grad            9.0   
48840  58       Private  151910.0     HS-grad            9.0   
48841  22       Private  201490.0     HS-grad            9.0   
48842  52  Self-emp-inc  287927.0     HS-grad            9.0   

           Martial Status         Occupation Relationship OrigEthn     Sex  \
48838  Married-civ-spouse       Tech-support         Wife    White  Female   
48839  Married-civ-spouse  Machine-op-inspct      Husband    White    Male   
48840             Widowed       Adm-clerical    Unmarried    White  Female   
48841       Never-married       Adm-clerical    Own-child    White    Male   
48842  Married-civ-spouse    Exec-managerial         Wife    White  Female   

       Capital Gain  Capital Loss  Hours per week        Country Target  
48838           0.0           0.0            38.0  United-States  <=50K  
48839           0.0           0.0            40.0  United-States   >50K  
48840           0.0           0.0            40.0  United-States  <=50K  
48841           0.0           0.0            20.0  United-States  <=50K  
48842       15024.0           0.0            40.0  United-States   >50K

In [13]:
data=original_data.copy()


data['Child'] = np.where(data['Relationship']=='Own-child', 'ChildYes', 'ChildNo')
data['OrigEthn'] = np.where(data['OrigEthn']=='White', 'CaucYes', 'CaucNo')

data=data.drop(columns=['fnlwgt','Relationship','Country','Education'])

data=data.replace('<=50K.','<=50K')
data=data.replace('>50K.','>50K')

data.tail()


Age     Workclass  Education-Num      Martial Status         Occupation  \
48838  27       Private           12.0  Married-civ-spouse       Tech-support   
48839  40       Private            9.0  Married-civ-spouse  Machine-op-inspct   
48840  58       Private            9.0             Widowed       Adm-clerical   
48841  22       Private            9.0       Never-married       Adm-clerical   
48842  52  Self-emp-inc            9.0  Married-civ-spouse    Exec-managerial   

      OrigEthn     Sex  Capital Gain  Capital Loss  Hours per week Target  \
48838  CaucYes  Female           0.0           0.0            38.0  <=50K   
48839  CaucYes    Male           0.0           0.0            40.0   >50K   
48840  CaucYes  Female           0.0           0.0            40.0  <=50K   
48841  CaucYes    Male           0.0           0.0            20.0  <=50K   
48842  CaucYes  Female       15024.0           0.0            40.0   >50K   

          Child  
48838   ChildNo  
48839   ChildNo  
48840   ChildNo  
48841  ChildYes  
48842   ChildNo

In [14]:
data_ohe=data.copy()

data_ohe['Target'] = np.where(data_ohe['Target']=='>50K', 1., 0.)
print(' -> In column Target: label >50K gets 1.')

data_ohe['OrigEthn'] = np.where(data_ohe['OrigEthn']=='CaucYes', 1., 0.)
print(' -> In column '+str('OrigEthn')+': label '+str('CaucYes')+' gets 1.')

data_ohe['Sex'] = np.where(data_ohe['Sex']=='Male', 1., 0.)
print(' -> In column '+str('Sex')+': label '+str('Male')+' gets 1.')

for col in ['Workclass', 'Martial Status', 'Occupation', 'Child']:
    if len(set(list(data_ohe[col])))==2:
        LabelThatGets1=data_ohe[col][0]
        data_ohe[col] = np.where(data_ohe[col]==LabelThatGets1, 1., 0.)
        print(' -> In column '+str(col)+': label '+str(LabelThatGets1)+' gets 1.')
    else:
        print(' -> In column '+str(col)+': one-hot encoding conversion with labels '+str(set(list(data_ohe[col]))))
        data_ohe=pd.get_dummies(data_ohe,prefix=[col],columns=[col])

data_ohe.tail()

 -> In column Target: label >50K gets 1.
 -> In column OrigEthn: label CaucYes gets 1.
 -> In column Sex: label Male gets 1.
 -> In column Workclass: one-hot encoding conversion with labels {'State-gov', 'Self-emp-not-inc', None, 'Federal-gov', 'Never-worked', 'Without-pay', 'Local-gov', nan, 'Self-emp-inc', 'Private'}
 -> In column Martial Status: one-hot encoding conversion with labels {'Married-spouse-absent', 'Married-AF-spouse', None, 'Divorced', 'Separated', 'Widowed', 'Married-civ-spouse', 'Never-married'}
 -> In column Occupation: one-hot encoding conversion with labels {'Exec-managerial', nan, 'Machine-op-inspct', 'Prof-specialty', 'Priv-house-serv', 'Tech-support', 'Adm-clerical', None, 'Armed-Forces', 'Protective-serv', 'Sales', 'Transport-moving', 'Handlers-cleaners', 'Farming-fishing', 'Craft-repair', 'Other-service'}
 -> In column Child: label ChildNo gets 1.


Age  Education-Num  OrigEthn  Sex  Capital Gain  Capital Loss  \
48838  27           12.0       1.0  0.0           0.0           0.0   
48839  40            9.0       1.0  1.0           0.0           0.0   
48840  58            9.0       1.0  0.0           0.0           0.0   
48841  22            9.0       1.0  1.0           0.0           0.0   
48842  52            9.0       1.0  0.0       15024.0           0.0   

       Hours per week  Target  Child  Workclass_Federal-gov  ...  \
48838            38.0     0.0    1.0                      0  ...   
48839            40.0     1.0    1.0                      0  ...   
48840            40.0     0.0    1.0                      0  ...   
48841            20.0     0.0    0.0                      0  ...   
48842            40.0     1.0    1.0                      0  ...   

       Occupation_Farming-fishing  Occupation_Handlers-cleaners  \
48838                           0                             0   
48839                           0                             0   
48840                           0                             0   
48841                           0                             0   
48842                           0                             0   

       Occupation_Machine-op-inspct  Occupation_Other-service  \
48838                             0                         0   
48839                             1                         0   
48840                             0                         0   
48841                             0                         0   
48842                             0                         0   

       Occupation_Priv-house-serv  Occupation_Prof-specialty  \
48838                           0                          0   
48839                           0                          0   
48840                           0                          0   
48841                           0                          0   
48842                           0                          0   

       Occupation_Protective-serv  Occupation_Sales  Occupation_Tech-support  \
48838                           0                 0                        1   
48839                           0                 0                        0   
48840                           0                 0                        0   
48841                           0                 0                        0   
48842                           0                 0                        0   

       Occupation_Transport-moving  
48838                            0  
48839                            0  
48840                            0  
48841                            0  
48842                            0  

[5 rows x 38 columns]

In [15]:
data_ohe=data_ohe.iloc[1:]

Finally extract the input and output (X and y) matrices as np.arrays for further analyses using sklearn, and split them into a learning and test sample. 

In [16]:
#extract the X and y np.arrays
y=data_ohe['Target'].values.reshape(-1,1)

data_ohe_wo_target=data_ohe.drop(columns=['Target'])

X_col_names=list(data_ohe_wo_target.columns)
X=data_ohe_wo_target.values


#split the learning and test samples
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

#print the np.array shapes 
print('n_train=',X_train.shape[0])
print('n_test=',X_test.shape[0])
print('p=',X_test.shape[1])

#center-reduce the arrays X_train and X_test to make sure all variables have the same scale
X_train=sk.preprocessing.scale(X_train)
X_test_NoScaling=X_test.copy()
X_test=sk.preprocessing.scale(X_test)

n_train= 32724
n_test= 16118
p= 37



### Classification with decision tree

We now train a <i>Decsion tree</i> on the data, which has the interest to be straightforwardly interpretable.


In [17]:
from sklearn.tree import DecisionTreeClassifier

clf_DT=DecisionTreeClassifier(max_depth=5)
clf_DT.fit(X_train,y_train.ravel())

y_test_pred_DT = clf_DT.predict(X_test)

#*** Uncomment the three raws below to see the decision rules ***
#from sklearn import tree
#dot_data = tree.export_graphviz(DTC_clf)
#print(dot_data)

Let's see now the prediction accuracy

This is the best average result so far. Remark however that altough the prediction are clearly the best for the obesrvations with y=0, they are clearly poor for y=1, which contains about 24&percnt; of the observations. There are even more false positive than true positive predictions.

### Classfication with positive discrimination

In [19]:
import random
def discriminate(X,y, p):
    n=len(y.ravel())
    nb_changes=int(n*p)
    # Randomly select and change the values
    indices_to_change = random.sample(range(n), nb_changes)
    z=y
    for idx in indices_to_change:
        if X[idx][X_col_names.index('Sex')]<0 and z[idx]==0.0:
            z[idx] = 1 - z[idx]
    return z



In [32]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier

# Define the number of splits (k) for cross-validation
num_splits = 10
disc_rate=0.0 #1 for full discrimination, 0 for no discrimination 
known_DI=0.35
p=0
C=2
clf_disc=DecisionTreeClassifier(max_depth=5)

S=X_test_NoScaling[:,X_col_names.index('Sex')].ravel()




# Create a KFold object to split the data
kf = KFold(n_splits=num_splits, shuffle=True, random_state=41)

# Split your data and train the model on each split
for train_index, test_index in kf.split(X_train):
    X_train_fold, X_test_fold = X_train[train_index], X_train[test_index]
    y_train_fold, y_test_fold = y_train.ravel()[train_index], y_train.ravel()[test_index]


    # Train the model on the current fold
    clf_disc.fit(X_train_fold, discriminate(X_train_fold, y_train_fold,p))
    y_test_pred_fold = clf_disc.predict(X_test_fold)
    acc=accuracy_score(y_test_fold.ravel(),y_test_pred_fold.ravel())
    tpr=np.sum((y_test_pred_fold.ravel()==1)*(y_test_fold.ravel()==1)) / np.sum(y_test_pred_fold.ravel()==1)
    tnr=np.sum((y_test_pred_fold.ravel()==0)*(y_test_fold.ravel()==0)) / np.sum(y_test_pred_fold.ravel()==0)

    cm = metrics.confusion_matrix(y_test_fold.ravel(),y_test_pred_fold.ravel(),labels=[0,1])

    print("\nAccuracy =",acc)
    print("True positive rate =",tpr)  #Rem: Equivalent to metrics.precision_score(y_test.ravel(), y_test_pred.ravel(), pos_label=1.)
    print("True negative rate =",tnr)
    print('\nConfusion matrix =')
    print(cm)

    S=X_test_fold[:,X_col_names.index('Sex')].ravel()
    DI=len([i for i in range(len(S)) if (y_test_pred_fold[i]==1.0 and S[i]<0)])/ len([i for i in range(len(S)) if (y_test_pred_fold[i]==1.0 and S[i]>0)])
    print('DI:',DI)
    if (known_DI-DI)*C>0 and (known_DI-DI)*C<1:
        p=(known_DI-DI)*C
        print(p)
    

    



Accuracy = 0.8499847234952643
True positive rate = 0.78719723183391
True negative rate = 0.8634508348794063

Confusion matrix =
[[2327  123]
 [ 368  455]]
DI: 0.12015503875968993
0.45968992248062013

Accuracy = 0.8124045218454018
True positive rate = 0.6070381231671554
True negative rate = 0.8664608259359321

Confusion matrix =
[[2245  268]
 [ 346  414]]
DI: 0.5325842696629214

Accuracy = 0.8075160403299725
True positive rate = 0.584931506849315
True negative rate = 0.8714117184427841

Confusion matrix =
[[2216  303]
 [ 327  427]]
DI: 0.6820276497695853

Accuracy = 0.8010999083409716
True positive rate = 0.5708762886597938
True negative rate = 0.8726471766119344

Confusion matrix =
[[2179  333]
 [ 318  443]]
DI: 0.8173302107728337

Accuracy = 0.8331295843520783
True positive rate = 0.687218045112782
True negative rate = 0.8703490602224779

Confusion matrix =
[[2269  208]
 [ 338  457]]
DI: 0.3739669421487603

Accuracy = 0.8279339853300733
True positive rate = 0.6656346749226006
True ne

In [34]:
from sklearn.metrics import accuracy_score
from sklearn import metrics

#### Results for DT
acc_DT=accuracy_score(y_test.ravel(),y_test_pred_DT.ravel())
tpr_DT=np.sum((y_test_pred_DT.ravel()==1)*(y_test.ravel()==1)) / np.sum(y_test_pred_DT.ravel()==1)
tnr_DT=np.sum((y_test_pred_DT.ravel()==0)*(y_test.ravel()==0)) / np.sum(y_test_pred_DT.ravel()==0)

cm_DT = metrics.confusion_matrix(y_test.ravel(),y_test_pred_DT.ravel(),labels=[0,1])

print("\nAccuracy for DT =",acc_DT)
print("True positive rate for DT =",tpr_DT)  #Rem: Equivalent to metrics.precision_score(y_test.ravel(), y_test_pred.ravel(), pos_label=1.)
print("True negative rate for DT=",tnr_DT)
print('\nConfusion matrix for DT =')
print(cm_DT)
S=X_test_NoScaling[:,X_col_names.index('Sex')].ravel()

y_test_pred_DT = clf_disc.predict(X_test).ravel()
DI_DT=len([i for i in range(len(S)) if (y_test_pred_disc[i]==1 and S[i]==0)])/ len([i for i in range(len(S)) if (y_test_pred_disc[i]==1 and S[i]==1)])


print('DI y_test_pred_DT =',DI_DT)


### Result for DT with positive discrimination



y_test_pred_disc= clf_disc.predict(X_test)

acc_disc=accuracy_score(y_test.ravel(),y_test_pred_disc.ravel())
tpr_disc=np.sum((y_test_pred_disc.ravel()==1)*(y_test.ravel()==1)) / np.sum(y_test_pred_disc.ravel()==1)
tnr_disc=np.sum((y_test_pred_disc.ravel()==0)*(y_test.ravel()==0)) / np.sum(y_test_pred_disc.ravel()==0)

cm_disc = metrics.confusion_matrix(y_test.ravel(),y_test_pred_disc.ravel(),labels=[0,1])

print("\nAccuracy with disc=",acc_disc)
print("True positive rate with disc=",tpr_disc)  #Rem: Equivalent to metrics.precision_score(y_test.ravel(), y_test_pred.ravel(), pos_label=1.)
print("True negative rate with disc=",tnr_disc)
print('\nConfusion matrix with disc=')
print(cm_disc)


S=X_test_NoScaling[:,X_col_names.index('Sex')].ravel()

y_test_pred_disc = clf_disc.predict(X_test).ravel()
DI_disc=len([i for i in range(len(S)) if (y_test_pred_disc[i]==1 and S[i]==0)])/ len([i for i in range(len(S)) if (y_test_pred_disc[i]==1 and S[i]==1)])


print('DI y_test_pred_disc =',DI_disc)



Accuracy for DT = 0.8460727137361955
True positive rate for DT = 0.7708253358925143
True negative rate for DT= 0.8605787019906757

Confusion matrix for DT =
[[11629   597]
 [ 1884  2008]]
DI y_test_pred_DT = 0.43793584379358436

Accuracy with disc= 0.8176572775778632
True positive rate with disc= 0.654057549304882
True negative rate with disc= 0.8565067178502879

Confusion matrix with disc=
[[11156  1070]
 [ 1869  2023]]
DI y_test_pred_disc = 0.43793584379358436
